# Generated by Django 5.1.7 on 2025-04-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_quiz_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='options',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
