# Generated by Django 5.1.7 on 2025-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_quiz_questions_alter_question_quiz_choice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="question_text",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="text",
        ),
        migrations.AddField(
            model_name="choice",
            name="option_text",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
