# Generated by Django 5.1.7 on 2025-04-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_text_question_question_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="order",
        ),
    ]
