# Generated by Django 5.1.7 on 2025-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
