# Generated by Django 5.1.7 on 2025-04-02 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_choice_order_question_order"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprogress",
            name="unique_user_lesson_progress",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="quiz_score",
        ),
        migrations.AddField(
            model_name="userprogress",
            name="course",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="core.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprogress",
            name="current_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.lesson",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="progress_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
