# Generated by Django 5.1.7 on 2025-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_userprogress_unique_user_lesson_progress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="choice",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
