# Generated by Django 5.1.7 on 2025-04-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_userprogress_completed_alter_choice_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_option_index",
        ),
        migrations.RemoveField(
            model_name="question",
            name="options",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="questions",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="current_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_in_enrollments",
                to="core.lesson",
            ),
        ),
        migrations.DeleteModel(
            name="UserProgress",
        ),
    ]
