# Generated by Django 5.1.7 on 2025-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
