# Generated by Django 5.1.7 on 2025-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_lesson_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="audio_transcription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
