# Generated by Django 5.1.7 on 2025-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_lesson_audio_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquizattempt",
            name="points_earned",
            field=models.IntegerField(default=0),
        ),
    ]
