# Generated by Django 5.1.7 on 2025-04-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userquizattempt_points_earned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquizattempt",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
