# Generated by Django 5.1.7 on 2025-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_userquizattempt_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("auto", "Auto")],
                default="auto",
                max_length=50,
            ),
        ),
    ]
