# Generated by Django 5.1.7 on 2025-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
