# Generated by Django 5.1.7 on 2025-04-04 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_achievement_userprofile_badges_userachievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_active",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rank",
            field=models.CharField(default="Beginner", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="badges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
