# Generated by Django 5.1.7 on 2025-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_userprofile_last_active_userprofile_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="lesson_pdfs/"),
        ),
    ]
