# Generated by Django 5.1.7 on 2025-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_lesson_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
