"""
Django settings for online_learning project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/ref/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'  # Replace with your actual secret key

DEBUG = True

ALLOWED_HOSTS = []  # Add the necessary host names when deploying

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # your app
    'ckeditor_uploader',  # CKEditor upload functionality
    'django_ckeditor_5',  # CKEditor 5
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'online_learning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core/templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.gamification_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_learning.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Use your database engine here (sqlite3, postgresql, etc.)
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'extends': 'django_ckeditor_5.configs.base',  # Extending default CKEditor5 config
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "strike", "|",
            "numberedList", "bulletedList", "|",
            "blockQuote", "code", "link", "horizontalLine", "|",
            "undo", "redo",
        ],
        "upload": {
            "image": {
                "types": ["jpeg", "png", "gif", "webp"]
            }
        },
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirects after login and logout
LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect after successful login
LOGOUT_REDIRECT_URL = '/'  # Redirect after logout

# settings.py

AUTH_USER_MODEL = 'core.CustomUser'  # Update this line to use the custom user model

# Email settings
# Configure these if you need to send emails
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Default email backend for development

# CSRF settings
CSRF_COOKIE_SECURE = False  # Set to True if using HTTPS

# Session settings
SESSION_COOKIE_SECURE = False  # Set to True if using HTTPS

# MEDIA SETTINGS
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

